#.
#Client-only settings for Modern Train Parts
[client]
	#.
	#The spacing between wire hangers
	# Default: 2
	# Range: > 1
	wire_hanger_spacing = 2
	#.
	#When lowered the bulkstorages can end lower than a full block depending by how much its lowered
	# Default: 0.0
	# Range: -1.0 ~ 0.0
	bulkstorage_randomheight_offset = 0.0
